program: main.py
entity: r252_bel
project: setup_tests

name: sweepdemo

command:
- ${env}
- ${interpreter}
- ${program}
- -- model
- gcn
- --dataset_type
- homo
- --dataset_name
- CIFAR10
- --dataset_type graph_homo 
- --graph_classification 
- true 
- ${args}

method: grid
parameters:

  with_sam:
    distribution: categorical
    values:
    - true
    - false

  batch_size:
    distribution: categorical
    values:
    - 8
    - 16
    - 32
    - 64
    - 128


  num_layers:
    distribution: categorical
    values:
    - 1
    - 3
    - 10

  hidden_dim:
    distribution: categorical
    values:
    - 4
    - 64
    - 128

  seed:  # number of folds
    distribution: categorical
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
